services:
  - type: web
    name: eunoia-backend
    env: python
    buildCommand: pip install -r backend/requirements-render.txt
    startCommand: cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: EUNOIA_USE_AGNO
        value: "true"
      - key: EUNOIA_ENABLE_MODELS
        value: "true"
