[phases.setup]
nixPkgs = ["python3", "python3Packages.pip"]

[phases.build]
cmds = [
  "python3 -m venv venv",
  "source venv/bin/activate",
  "pip install -r requirements-render.txt"
]

[start]
cmd = "source venv/bin/activate && python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT"
