name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  backend:
    name: Backend (Python)
    runs-on: ubuntu-latest
    env:
      EUNOIA_ENABLE_MODELS: '0'
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Static check (syntax)
        run: |
          python -m py_compile *.py

      - name: Run tests (if available)
        run: |
          if [ -f run_tests.py ]; then python run_tests.py; else pytest -q || echo "No tests or failures; continuing for early stage"; fi
        continue-on-error: true

  frontend:
    name: Frontend (Node)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci --no-audit --no-fund; else npm install --legacy-peer-deps --no-audit --no-fund; fi

      - name: Lint
        run: npm run lint || echo "Lint warnings/errors allowed at early stage"

      - name: Build (if present)
        run: |
          npm run build --if-present

      - name: Test (lenient for early stage)
        run: |
          npm test --if-present -- --watchAll=false || echo "Tests failed or not present; continuing due to early-stage leniency"
        continue-on-error: true
